### PR TITLE
Fix issue where a tuple was incorrectly implicitly used, causing JSON objects to be nested rather than added to a single array

### PR DESCRIPTION
**Pull request by imeesa**
Fix issue where a tuple was incorrectly implicitly used, causing JSON objects to be nested rather than added to a single array

### CODE REVIEW

**Comment by imeesa** [comment]
cc @EngurRuzgar

**Comment by Nucceteere** [comment]
returns a null
image
image

**Comment by imeesa** [comment]
hm

**Comment by Nucceteere** [comment]
even when the player is turned to address returns a null

**Comment by imeesa** [comment]
is this on the prod db?

**Comment by Nucceteere** [comment]
yes

**Comment by imeesa** [comment]
code was a bit wonky, i had to copy the fixes to a new spot

try again?

**Comment by Nucceteere** [comment]
image
image
image

**Comment by imeesa** [comment]
what's in raw data?

**Comment by Nucceteere** [comment]
image

**Comment by imeesa** [comment]
could you try print(length)?
we should probably do this in discord

**Comment by Nucceteere** [comment]
github is fine

**Comment by Nucceteere** [comment]
print(length) prints 4

**Comment by imeesa** [comment]
hm
there was an incorrect number used before, how about now?

**Comment by Nucceteere** [comment]
Still same. Player returns null, Address returns an empty array

**Comment by imeesa** [comment]
is the code up to date? that was an issue in the very first commit but was fixed in the second one
try pulling from my fork

**Comment by Nucceteere** [comment]
I replaced the whole file but ill try to pull then run it

**Comment by imeesa** [comment]
alr

**Comment by Nucceteere** [comment]
still same
using prod db

**Comment by imeesa** [comment]
hm
can you send the code you're using in plaintext on discord?

**Comment by imeesa** [comment]
I was using a reassignment instead of an in place change. it has been fixed. dont deploy it tho, theres sql injection

**Comment by Nucceteere** [comment]
Seems to work. Thanks

**Pull request merged**
